from typing import Protocol


class CacheProtocol(Protocol):
    async def get(self, key: str) -> str | None: ...

    async def set(self, key: str, value: str, ttl: int | None = None) -> bool: ...

    async def delete(self, key: str) -> bool: ...
